In [1]:
import tensorflow as tf

import numpy as np
import pandas as pd


from transformers import BertTokenizer, TFBertModel

2024-07-14 06:12:00.522193: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:479] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-07-14 06:12:00.542324: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:10575] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-07-14 06:12:00.542356: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1442] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-07-14 06:12:00.555358: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-07-14 06:12:01.108625: W tensorflow/compiler/tf

In [2]:
tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")

def tokenize_function(text):
    return tokenizer(text, return_tensors='tf', max_length=500, truncation=True, padding='max_length')

In [3]:
text = '''He was the son of a poor cottager, and while still a boy he grew restless and left home.
When he was barely thirteen years old he buckled on his satchel and set forth from his
native woodland parish. Despite the dissuasion of villagers who could speak from
'experience,' he went to Vienna to learn a trade there. This was in the fiftieth year of the
last century. It was a sore trial, that of deciding to leave home and face the unknown,
with three gulden in his pocket. By when the boy of thirteen was a lad of seventeen and
had passed his apprenticeship examination as a craftsman he was not content. Quite the
contrary. The persistent economic depression of that period and the constant want and
misery strengthened his resolution to give up working at a trade and strive for
'something higher.' As a boy it had seemed to him that the position of the parish priest
in his native village was the highest in the scale of human attainment; but now that the
big city had enlarged his outlook the young man looked up to the dignity of a State
official as the highest of all. With the tenacity of one whom misery and trouble had
already made old when only half-way through his youth the young man of seventeen
obstinately set out on his new project and stuck to it until he won through. He became a
civil servant. He was about twenty-three years old, I think, when he succeeded in
making himself what he had resolved to become. Thus he was able to fulfil the promise
he had made as a poor boy not to return to his native village until he was 'somebody.'
He had gained his end. But in the village there was nobody who had remembered him
as a little boy, and the village itself had become strange to him.
Now at last, when he was fifty-six years old, he gave up his active career; but he could
not bear to be idle for a single day. On the outskirts of the small market town of
Lambach in Upper Austria he bought a farm and tilled it himself. Thus, at the end of a
long and hard-working career, he came back to the life which his father had led.
It was at this period that I first began to have ideals of my own. I spent a good deal of
time scampering about in the open, on the long road from school, and mixing up with
some of the roughest of the boys, which caused my mother many anxious moments. All
this tended to make me something quite the reverse of a stay-at-home.'''

In [4]:
tokend_result = tokenize_function(text)

2024-07-14 06:12:03.580743: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:998] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-07-14 06:12:03.581624: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:998] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-07-14 06:12:03.581791: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:998] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-

In [5]:
input_ids = tokend_result["input_ids"]
attention_mask = tokend_result["attention_mask"]

In [6]:
print(attention_mask)

tf.Tensor(
[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1

In [7]:
model = tf.keras.models.load_model("./baseline0713_22.h5", custom_objects={"TFBertModel": TFBertModel})

In [8]:
pred_result = model.predict([input_ids, attention_mask])
print(pred_result)
pred_result = np.round(pred_result)

pred_result

1/1 [==============================] - 7s 7s/step
[[0.02636496 0.8916771  0.16665787 0.15165159]]


array([[0., 1., 0., 0.]], dtype=float32)